### ISSUE TITLE
Command Typo on Invoke-AtomicTest -All -GetPrereqs

### ISSUE THREAD

**Issue by merlin-ke** [redcanaryco/invoke-atomicredteam#106]
The command` Invoke-AtomicTest -All -GetPrereqs`  on the wiki https://github.com/redcanaryco/invoke-atomicredteam/wiki/Offline-Installation -> Steps to take from the online system section doesn't work. 
The right command is `Invoke-AtomicTest All -GetPrereqs`

**Comment by vi-or-die** [comment]
Ill confirm @merlin-ke! Great find and that is the fix.

**Comment by clr2of8** [comment]
I corrected this. Thank you!
