### ISSUE TITLE
Provide process id and process exit code to loggers

### ISSUE THREAD

**Issue by hxnoyd** [redcanaryco/invoke-atomicredteam#107]
This is a feature request.

Would it be possible to pass Invoke-Process $Process.Id and $Process.Exit code to loggers via Write-ExecutionLog?
The process id is specially helpful when correlating with EDR timelines to validate detections.

Thanks in advance!

**Comment by clr2of8** [comment]
Great idea and YES! We got this added with PR #116 on April 15th
