### ISSUE TITLE
Installation atomicRedTeam failed

### ISSUE THREAD

**Issue by irfanh14** [redcanaryco/invoke-atomicredteam#109]
PS C:\> IEX (IWR 'https://raw.githubusercontent.com/redcanaryco/invoke-atomicredteam/master/install-atomicredteam.ps1' -UseBasicParsing);
>> Install-AtomicRedTeam -getAtomics -Force -noPayloads
Installation of AtomicRedTeam Failed.
Cannot convert null to type "System.DateTime".

I have these issues during installation. anyone can help? Installed on win 11

Thanks.

**Comment by clr2of8** [comment]
We have seen this occasionally and believe that it is related to the OS region settings but we haven't been able to pinpoint it. Have you gotten past this? If not, could you share your settings as shown below so we can duplicate the issue? 
![image](https://github.com/redcanaryco/invoke-atomicredteam/assets/22311332/137a9246-b5f4-413e-b62c-675b27897d6b)

**Comment by clr2of8** [comment]
Another user with the same problem was able to solve it as follows:

**I was actually able to fix this, it was an issue on my side.
I needed to upgrade my PS modules of PowerShellGet and PackageManagement (both were at 1.0.0.1 while new versions are 2.2.5 and 1.4.8.1 respectively) and delete the old ones from my machine.
That fixed the issue for me**

**Comment by miharix** [comment]
Hi,

to save some noob like myself me some google time... commands are:

```
Install-PackageProvider Nuget –Force
Install-Module –Name PowerShellGet –Force
Install-Module –Name PackageManagement –Force
```
And then restart PowerShell

In my case (Win 10 pro 10.0.19045 build 19045 - ENG - keyboard Sl-SI, Locale Sl-SI / or English (World)  ) calling only
`update-module`
also produced  - Cannot convert null to type "System.DateTime".
After update and PS restart "update-module" doesn't create error
and atomicRedTeam installations works.
