### ISSUE TITLE
Idea: Add parameter to output test GUID before running command

### ISSUE THREAD

**Issue by MSAdministrator** [redcanaryco/invoke-atomicredteam#142]
### Use-cases
As a user, I want to output the current test GUID before running the test so that it will be easier to identify which test ran in logging mechanisms.

Another idea is to also set this to an environment variable as well.

### Proposal

Add an optional Boolean command line parameter named 

—AddGUIDPrefix

which would then prefix the command with something like 

echo “{TEST GUID}” && {run test normally}

### References
https://atomicredteam.slack.com/archives/CTXD5274M/p1689173909822249

**Comment by clr2of8** [comment]
It appears that the method that the AtomicRunner functionality provides as described [here](https://github.com/redcanaryco/invoke-atomicredteam/wiki/Continuous-Atomic-Testing) is ideal as the host running atomic tests is renamed to include the GUID automatically before each test and many/most security products including the hostname in their telemetry. In consideration of this, I'll close this request for now. Thank you
