### ISSUE TITLE
Use of relative paths for atomics folder

### ISSUE THREAD

**Issue by 2XXE-SRA** [redcanaryco/invoke-atomicredteam#17]
I was attempting to use this execution framework to test some automation and kept running into an issue where the system was saying the path was not found for an included bat file. It turns out that the -PathToAtomicsFolder argument does not support relative paths. Once I switched to absolute paths, it worked. 

As a test, I added the following line to Public/Invoke-AtomicTest.ps1 at the start of the processs block:

```
$PathToAtomicsFolder = (Resolve-Path $PathToAtomicsFolder).Path
```

and I was able to use relative paths for the atomics folder. 

Do you foresee any issues with this approach?

**Comment by clr2of8** [comment]
This seems reasonable. Would you like to submit a Pull Request with this change? If not, I can get a PR going but wanted to give you the opportunity if you wanted to.

**Comment by 2XXE-SRA** [comment]
opened

**Comment by clr2of8** [comment]
Merged, thank you!

**Comment by 2XXE-SRA** [comment]
Thanks for the quick turnaround!
