### ISSUE TITLE
Offline usage of -GetPrereqs Timed out after 0 seconds

### ISSUE THREAD

**Issue by ndex11** [redcanaryco/invoke-atomicredteam#191]
I have installed Atomics and Invoke-atomicred on the online machine.
Then run command Invoke-AtomicTest All -GetPrereqs and prereqs were downloaded and installed.
I have copied whole AtomicsRed directory to the same location on the offline machine.
When I try to run command Invoke-AtomicTest All -GetPrereqs on the offline machine I am getting error  Process Timed out after 0 seconds, use '-TimeoutSeconds' to specify a different timeout 
This error is generated for every test and no prereqs have being installed into the system.

Example:
Attempting to satisfy prereq: Computer must have python 3 installed
VERBOSE: Replacing inputArgs with user specified values, or default values if none provided
VERBOSE: Replacing inputArgs with user specified values, or default values if none provided
VERBOSE: Invoking Atomic Tests using defined executor
VERBOSE: Perform operation 'Enumerate CimInstances' with following parameters, ''namespaceName' = root\cimv2,'className' = Win32_Process'.
VERBOSE: Operation 'Enumerate CimInstances' complete.
Process Timed out after 0 seconds, use '-TimeoutSeconds' to specify a different timeout
VERBOSE: Invoking Atomic Tests using defined executor
VERBOSE: Perform operation 'Enumerate CimInstances' with following parameters, ''namespaceName' = root\cimv2,'className' = Win32_Process'.
VERBOSE: Operation 'Enumerate CimInstances' complete.
VERBOSE: Perform operation 'Enumerate CimInstances' with following parameters, ''namespaceName' = root\cimv2,'className' = Win32_Process'.
VERBOSE: Operation 'Enumerate CimInstances' complete.
VERBOSE: Perform operation 'Enumerate CimInstances' with following parameters, ''namespaceName' = root\cimv2,'className' = Win32_Process'.
VERBOSE: Operation 'Enumerate CimInstances' complete.
Process Timed out after 0 seconds, use '-TimeoutSeconds' to specify a different timeout
VERBOSE: Invoking Atomic Tests using defined executor
VERBOSE: Perform operation 'Enumerate CimInstances' with following parameters, ''namespaceName' = root\cimv2,'className' = Win32_Process'.
VERBOSE: Operation 'Enumerate CimInstances' complete.
Process Timed out after 0 seconds, use '-TimeoutSeconds' to specify a different timeout
Failed to meet prereq: Computer must have python 3 installed

**Comment by ndex11** [comment]
There is no check, If installer already exists in ExternalPayloads directory, in get_prereq_command in yaml file. Would be great to check if installer exists and then skip Invoke-WebRequest which is causing timeout error in my opinion.

**Comment by Jake151** [comment]
Hi @ndex11 - This bug should be fixed in #190. You'll need to redownload invoke-atomicredteam from the repo for this to work.

**Comment by cyberbuff** [comment]
Appreciate your help @Jake151 Thank you :)
