### ISSUE TITLE
Suggestion: add warning when passing an InputArgs that doesn't exist

### ISSUE THREAD

**Issue by cnotin** [redcanaryco/invoke-atomicredteam#35]
Sometimes we make a mistake and we pass a non-existing or mistyped arg in `-InputArgs`. Invoke-AtomicRedTeam doesn't complain in such cases rendering the error silent...
I suggest adding an explicit error message when trying to use an invalid input arg to prevent such silly mistakes :)

**Comment by clr2of8** [comment]
with `-verbose` option you'll see the warning now
