### ISSUE TITLE
T1158  no longer works.

### ISSUE THREAD

**Issue by leebaird** [redcanaryco/invoke-atomicredteam#43]
https://github.com/redcanaryco/invoke-atomicredteam/wiki/Specify-Custom-Input-Arguments

T1158  no longer works.

ERROR: C:\AtomicRedTeam\atomics\T1158\T1158.yaml does not exist
Check your Atomic Number and your PathToAtomicsFolder parameter

**Comment by clr2of8** [comment]
Hello leebaird, thanks for reaching out. This can definitely come as a surprise but the Mitre ATT&CK numbering schema recently changed. You can found out more about it [here](https://medium.com/mitre-attack/attack-subs-what-you-need-to-know-99bce414ae0b). In the case of T1158 it was renumbered and became part of a sub-technique as shown below.

![image](https://user-images.githubusercontent.com/22311332/89113139-3b7d3e00-d42a-11ea-8657-862a3ed31bc8.png)

**Comment by clr2of8** [comment]
You can now execute the same tests using the new subtechnique ID of T1164.001. If you have more questions I'd be happy to discuss with you over on our slack workspace https://slack.atomicredteam.io/ (@OrOneEqualsOne)
