### ISSUE TITLE
Atomic-GUI Error

### ISSUE THREAD

**Issue by DefSecSentinel** [redcanaryco/invoke-atomicredteam#44]
Everything else works perfectly. When I run Start-Atomic GUI I receive the following error. I have tried specifying a different port but I continue to receive this error and am unable to access the GUI. I've also tried re-installing the UniversalDashboard module with no luck.

Start-Process: /home/vagrant/AtomicRedTeam/invoke-atomicredteam/Public/Start-AtomicGUI.ps1:263
Line |
 263 |      start-process http://localhost:$port
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | This command cannot be run due to the error: No such file or directory.

**Comment by DefSecSentinel** [comment]
I'm running on a CentOS 7 box with the latest version of Powershell Core installed

**Comment by clr2of8** [comment]
After running start-atomicgui (and ignoring that error), can you visit http://localhost:8487 in your browser and see if the GUI is working in your browser?  Also, are you on the Slack Atomic Red Team workspace where we can chat interactively perhaps? I'm @OrOneEqualsOne over there.

**Comment by clr2of8** [comment]
I think I heard that you got this figured out, so closing for now.
