### ISSUE TITLE
[Question] Custom yaml with Invoke-Atomic

### ISSUE THREAD

**Issue by jwb4k3r** [redcanaryco/invoke-atomicredteam#56]
Looking through documentation, I may have missed something, but is it possible to run custom yaml with Invoke-Atomic, given that it fits the standard yaml format for ART? Thanks in advance!

**Comment by clr2of8** [comment]
If you have your own yaml of the same format, you can put it in whatever directory you want and then point to it when you execute the test using the `PathToAtomicsFolder` switch.

https://github.com/redcanaryco/invoke-atomicredteam/wiki/Execute-Atomic-Tests-(Local)#execute-all-tests-from-a-specific-directory

Invoke-AtomicTest T1111 -PathToAtomicsFolder C:\mycustompath\myatomics

In this example, your yaml file would be here C:\mycustompath\myatomics\T1111\T1111.yaml

**Comment by clr2of8** [comment]
You can also put the following in your powershell profile to set your own default for `PathToAtomicsFolder` so you don't need to include it on the command line every time. This is handy if you will be mostly executing from this custom folder.

`$PSDefaultParameterValues = @{"Invoke-AtomicTest:PathToAtomicsFolder"="C:\mycustompath\myatomics"}`

**Comment by jwb4k3r** [comment]
Thank you so much for the clarification.  That is just what I was looking for!
