### ISSUE TITLE
"Cannot convert null to type System.DateTime" when installing  Invoke-AtomicRedTeam

### ISSUE THREAD

**Issue by secTeach** [redcanaryco/invoke-atomicredteam#70]
I run into an error: "Cannot convert null to type System.DateTime" 
>  IEX (New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/redcanaryco/invoke-atomicredteam/master/install-atomicredteam.ps1')

> Install-AtomicRedTeam -Force
Installation of AtomicRedTeam Failed.
Cannot convert null to type "System.DateTime".

> Install-AtomicRedTeam -InstallPath "C:\Windows\Temp" -Force
Installation of AtomicRedTeam Failed.
Cannot convert null to type "System.DateTime".

**Comment by Cor-J** [comment]
Hello,

@secTeach Did you manage to bypass this issue?

**Comment by clr2of8** [comment]
I believe this is an issue with your PowerShell environment. For example, if you run `Get-InstalledModule` do you receive the same error? There are some suggested work arounds here. https://github.com/PowerShell/PowerShellGetv2/issues/135
