### ISSUE TITLE
Idea: Get-AtomicStatistics function to pull stats on atomics directory

### ISSUE THREAD

**Issue by mgraeber-rc** [redcanaryco/invoke-atomicredteam#71]
We get a lot of question about what atomic red team has/doesn't have in terms of coverage and often times the answer is present by scraping the atomic YAML and hacking together a number. For example, how many atomic test are applicable to macos? What percentage of tests are applicable to linux, etc.

What common questions do you have of the atomics directory in atomic-red-team? What output might you like to see from a Get-AtomicStatistics function? Add your feedback to this issue. Thank you!

**Comment by briancdonohue** [comment]
Not sure this is possible with PowerShell (or in scope), but it would be neat to be able to search the _contents_ of tests. For example, maybe I want to know every test that leverages `runddl32.exe` (including those that don't map to it).

**Comment by clr2of8** [comment]
I believe a soon to be revealed feature of atomicredteam.io is going to fulfill this. Hang on just a little longer ...
