### ISSUE TITLE
Error During Remote Windows to Windows Execution of Prereqs

### ISSUE THREAD

**Issue by clr2of8** [redcanaryco/invoke-atomicredteam#77]
"The system cannot find the file specified" 

![image](https://user-images.githubusercontent.com/22311332/138601650-81358027-0b68-4ab5-b460-489c199acb6a.png)

**Comment by tahaelgraini** [comment]
Hello
I noticed that as well. In Invoke-AtomicTest.ps1 on line 143 
        $PathToPayloads = if ($Session) { "$tmpDir`AtomicRedTeam" }  else { $PathToAtomicsFolder }

which means the remote machine should have the AtomicRedTeam folder in the $env:temp folder already?

Thank you

**Comment by clr2of8** [comment]
fixed in pr #81
