### ISSUE TITLE
Windows install uses incorrect install path for Invoke-AtomicRedTeam

### ISSUE THREAD

**Issue by rickhenderson** [redcanaryco/invoke-atomicredteam#78]
The web page says the atomics will be stored in (usually) C:\AtomicRedTeam\atomics and they are.

When I ran the command to install AtomicRedTeam, the Invoke-atomicredteam.ps1 file was placed at C:\Users\fauxmal\Documents\WindowsPowerShell\Modules\Invoke-AtomicRedTeam\1.0.0.0.

After moving the Invoke-AtomicRedTeam folder to C:\AtomicRedTeam, running the command to import the module during a new powershell session fails, because the command is stored in a subfolder named 1.0.0.0.

Let me know if you require more information.

I installed using Windows Terminal.

**Comment by clr2of8** [comment]
Yes, this is a little confusing and I've just updated the Wiki based on your feedback. If you use the `Install-Module` command, the installation goes to the folder you showed and you actually don't need to move it and you don't need to worry about importing the module manually or via your PowerShell profile. Let me know if you still have questions. I'm more responsive on the [Atomic Red Team Slack workspace](https://slack.atomicredteam.io/) as @OrOneEqualsOne than here.
