### ISSUE TITLE
How to query the output?

### ISSUE THREAD

**Issue by nimaforoughi** [redcanaryco/invoke-atomicredteam#84]
How can we search amongst the output . for example querying all the techniques or tests which contain the word of "SMB". 
Is there a way to do it directly without saving the output file?
I want to find all the Tests that are related to "SMB" for example

**Comment by clr2of8** [comment]
My suggestion is to use the search feature provided on GitHub. In this case you could go to the [Atomic Red Team Project](https://github.com/redcanaryco/atomic-red-team) and search for SMB.
