### ISSUE TITLE
Invoke-ExecuteCommand: Issue with backslashes being escaped

### ISSUE THREAD

**Issue by danf42** [redcanaryco/invoke-atomicredteam#91]
The backslash at the end of the find command that contain `-exec` is incorrectly being escaped.  

For example, the command for atomic-test [T1552.004-3](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1552.004/T1552.004.md#atomic-test-3---copy-private-ssh-keys-with-cp) is `find #{search_path} -name id_rsa -exec cp --parents {} #{output_folder} \;`.   After it is escaped the command becomes `find / -name id_rsa -exec cp --parents {} /tmp/art-staging \\;`.  An extra backslash is added causing the following error when executed `find: missing argument to -exec`.  

Found this escaping scheme is causing issues for other tests, [T1552.004-4](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1552.004/T1552.004.md#atomic-test-4---copy-private-ssh-keys-with-rsync) and [T1217](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1217/T1217.md#atomic-test-1---list-mozilla-firefox-bookmark-database-files-on-linux)

Updating the command to remove the backslash escaping does resolve the errors with the find commands
From:
```
$finalCommand = $finalCommand -replace "[\\`"]", "`\$&"
```
To:
```
$finalCommand = $finalCommand -replace "[`"]", "`\$&"
```
It looks like that fix was proposed in PR #24 but later was enhanced to the current code submitted in PR #33

Saw that the escape logic was removed from the command_prompt executor block.  Attempted to remove the line from the bash/sh logic bloc, but it broke atomic-test [T1083-4](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1083/T1083.md#atomic-test-4---nix-file-and-directory-discovery-2)

**Comment by clr2of8** [comment]
Thank you for the PR to fix!
