### ISSUE TITLE
Wiki Command Typo

### ISSUE THREAD

**Issue by Gborgman05** [redcanaryco/invoke-atomicredteam#97]
Under Execution Logging page, Redirect Output From Test Execution to a File section: `Invoke-AtomicTest tT1027 -TestNumbers 2 *>&1 | Tee-Object atomic-out.txt -Append` should be changed to `Invoke-AtomicTest T1027 -TestNumbers 2 *>&1 | Tee-Object atomic-out.txt -Append` removing the extra t.

**Comment by clr2of8** [comment]
Got it fixed. Thanks!
